dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install git+https://github.com/arose/nglview
  - pip install -e .
  - pip install -r test_requirements.txt
  - jupyter-nbextension enable nglview --py --sys-prefix

script: 
  - flake8
  - pytest

branches:
  only:
    - master
