dist: xenial

language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -e .
  - pip install -r test_requirements.txt
  - jupyter-nbextension enable nglview --py --sys-prefix

script: 
  - flake8
  - pytest

branches:
  only:
    - master
